name: Sync GitHub Labels via CLI

on:
  push:
    branches:
      - main
      - label-sync-test   # 테스트용 브랜치 포함
    paths:
      - '.github/labels.yml'

jobs:
  sync-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN | gh auth login --with-token

      - name: Show labels.yml content for debug
        run: cat .github/labels.yml

      - name: Sync labels from labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh label sync .github/labels.yml
