name: Sync GitHub Labels

on:
  push:
    branches:
      - main
      - chore/3-label-organisation
    paths:
      - .github/labels.yml

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
